runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /models
  static_dir: models

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
